name: Update README

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: Readme-Workflows/recent-activity@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "ðŸ’  | Update Lorenzo0111/Lorenzo0111 activity"
          MAX_LINES: 10
          
          URL_TEXT: "{REPO}{ID}"
          
          ISSUE_OPENED: "![issueOpened] **Issue opened:** {URL}"
          ISSUE_CLOSED: "![issueClosed] **Issue closed:** {URL}"
          PR_OPENED: "![pullRequestOpened] **Pull request opened:** {URL}"
          PR_CLOSED: "![pullRequestClosed] **Pull request closed:** {URL}"
          PR_MERGED: "![pullRequestMerged] **Pull request merged:** {URL}"
          COMMENTS_ACTIVITY: "![comment] **Commented:** {URL}"